spring.application.name=payment-service
server.port=8089

spring.datasource.url=jdbc:mysql://localhost:3306/flowboard_payment?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}

# Razorpay Test Keys (Dummy for now)
razorpay.key.id=rzp_test_So00bf10zdkL9B
razorpay.key.secret=${RAZORPAY_KEY_SECRET}

# Service URLs
workspace.service.url=http://localhost:8082
