# App name
spring.application.name=workspace-service

# Server port
server.port=8082

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://localhost:3306/flowboard_workspace?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ================= EUREKA =================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Force localhost in Eureka (IMPORTANT FIX)
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}

# ================= JWT =================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
